//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdvertisementID { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string Image { get; set; }
        public int Type { get; set; }
        public string Link { get; set; }
        public int State { get; set; }
        public System.DateTime Time { get; set; }
        public int OrderBy { get; set; }
    }
}
