//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ComplaintID { get; set; }
        public int Type { get; set; }
        public int InitiativeUserID { get; set; }
        public Nullable<int> PassivityUserID { get; set; }
        public Nullable<int> CirclePostID { get; set; }
        public System.DateTime Time { get; set; }
        public string Reason { get; set; }
    
        public virtual CirclePost CirclePost { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
