//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entity : DbContext
    {
        public Entity()
            : base("name=Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advertisement> Advertisement { get; set; }
        public virtual DbSet<CircleManage> CircleManage { get; set; }
        public virtual DbSet<CirclePost> CirclePost { get; set; }
        public virtual DbSet<CirclePostLog> CirclePostLog { get; set; }
        public virtual DbSet<CirclePostReply> CirclePostReply { get; set; }
        public virtual DbSet<CirclePostReplyChild> CirclePostReplyChild { get; set; }
        public virtual DbSet<CircleType> CircleType { get; set; }
        public virtual DbSet<Complaint> Complaint { get; set; }
        public virtual DbSet<DiscountCoupon> DiscountCoupon { get; set; }
        public virtual DbSet<DiscountCouponType> DiscountCouponType { get; set; }
        public virtual DbSet<ExperienceLevel> ExperienceLevel { get; set; }
        public virtual DbSet<Good> Good { get; set; }
        public virtual DbSet<GoodCart> GoodCart { get; set; }
        public virtual DbSet<GoodChild> GoodChild { get; set; }
        public virtual DbSet<GoodCollection> GoodCollection { get; set; }
        public virtual DbSet<GoodEvaluate> GoodEvaluate { get; set; }
        public virtual DbSet<GoodExperience> GoodExperience { get; set; }
        public virtual DbSet<GoodExperienceReply> GoodExperienceReply { get; set; }
        public virtual DbSet<GoodExperienceReplyChild> GoodExperienceReplyChild { get; set; }
        public virtual DbSet<GoodFilter> GoodFilter { get; set; }
        public virtual DbSet<GoodFilterTag> GoodFilterTag { get; set; }
        public virtual DbSet<GoodGategory> GoodGategory { get; set; }
        public virtual DbSet<GoodHome> GoodHome { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderExtend> OrderExtend { get; set; }
        public virtual DbSet<OrderLog> OrderLog { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserAddress> UserAddress { get; set; }
        public virtual DbSet<UserBlacklist> UserBlacklist { get; set; }
        public virtual DbSet<UserExtend> UserExtend { get; set; }
        public virtual DbSet<UserGradeLog> UserGradeLog { get; set; }
        public virtual DbSet<UserLog> UserLog { get; set; }
        public virtual DbSet<UserSMS> UserSMS { get; set; }
        public virtual DbSet<WholeFieldActivity> WholeFieldActivity { get; set; }
        public virtual DbSet<Welfare> Welfare { get; set; }
        public virtual DbSet<UserLetter> UserLetter { get; set; }
    }
}
