//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienceLevel
    {
        public int ExperienceLevelID { get; set; }
        public int ExperienceLevelValue { get; set; }
        public int ExperienceValueMin { get; set; }
        public int ExperienceValueMax { get; set; }
        public string NameMan { get; set; }
        public string NameWoman { get; set; }
    }
}
