//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodEvaluate
    {
        public int GoodEvaluateID { get; set; }
        public int GoodGategoryID { get; set; }
        public int GoodID { get; set; }
        public int UserID { get; set; }
        public int State { get; set; }
        public System.DateTime Time { get; set; }
        public decimal Score { get; set; }
        public string Detail { get; set; }
        public string Images { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual GoodGategory GoodGategory { get; set; }
        public virtual User User { get; set; }
    }
}
