//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.GoodCart = new HashSet<GoodCart>();
            this.GoodChild = new HashSet<GoodChild>();
            this.GoodCollection = new HashSet<GoodCollection>();
            this.GoodEvaluate = new HashSet<GoodEvaluate>();
            this.GoodExperience = new HashSet<GoodExperience>();
            this.GoodExperienceReply = new HashSet<GoodExperienceReply>();
            this.GoodExperienceReplyChild = new HashSet<GoodExperienceReplyChild>();
            this.GoodFilter = new HashSet<GoodFilter>();
            this.GoodHome = new HashSet<GoodHome>();
            this.Good1 = new HashSet<Good>();
            this.Good2 = new HashSet<Good>();
        }
    
        public int GoodID { get; set; }
        public int GoodGategoryID { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public decimal BidPrice { get; set; }
        public decimal RealPrice { get; set; }
        public int State { get; set; }
        public string Detail { get; set; }
        public string ImageList { get; set; }
        public string Image { get; set; }
        public int SalesVolume { get; set; }
        public int EvaluateNum { get; set; }
        public decimal EvaluateValue { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int OrderBy { get; set; }
        public int Repertory { get; set; }
        public decimal MaxPrice { get; set; }
    
        public virtual GoodGategory GoodGategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodCart> GoodCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodChild> GoodChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodCollection> GoodCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodEvaluate> GoodEvaluate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodExperience> GoodExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodExperienceReply> GoodExperienceReply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodExperienceReplyChild> GoodExperienceReplyChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodFilter> GoodFilter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodHome> GoodHome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Good> Good1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Good> Good2 { get; set; }
    }
}
