//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodFilter
    {
        public int GoodFilterTagID { get; set; }
        public int GoodId { get; set; }
        public int GoodGategoryID { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual GoodFilterTag GoodFilterTag { get; set; }
        public virtual GoodGategory GoodGategory { get; set; }
    }
}
