//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodChild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodChild()
        {
            this.GoodCart = new HashSet<GoodCart>();
        }
    
        public int GoodChildID { get; set; }
        public int GoodId { get; set; }
        public int GoodGategoryID { get; set; }
        public int Repertory { get; set; }
        public string Specification { get; set; }
        public decimal AddPrice { get; set; }
        public int SalesVolume { get; set; }
        public int State { get; set; }
        public string Image { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int OrderBy { get; set; }
    
        public virtual Good Good { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodCart> GoodCart { get; set; }
        public virtual GoodGategory GoodGategory { get; set; }
    }
}
