//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderLog = new HashSet<OrderLog>();
        }
    
        public string OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int State { get; set; }
        public int Num { get; set; }
        public int GoodID { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string LogisticsNumber { get; set; }
        public string LogisticsCompany { get; set; }
        public string LogisticsAddress { get; set; }
        public string LogisticsTel { get; set; }
        public string LogisticsPerson { get; set; }
        public Nullable<int> DiscountCouponID { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Remark { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual DiscountCoupon DiscountCoupon { get; set; }
        public virtual User User { get; set; }
        public virtual OrderExtend OrderExtend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLog> OrderLog { get; set; }
    }
}
