//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLetter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserLetter()
        {
            this.UserLetter1 = new HashSet<UserLetter>();
        }
    
        public int UserLetterID { get; set; }
        public Nullable<int> FatherUserLetterID { get; set; }
        public int InitiativeUserID { get; set; }
        public int PassivityUserID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Text { get; set; }
        public int Type { get; set; }
        public int State { get; set; }
        public Nullable<int> CirclePostID { get; set; }
    
        public virtual CirclePost CirclePost { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLetter> UserLetter1 { get; set; }
        public virtual UserLetter UserLetter2 { get; set; }
    }
}
