//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSMS
    {
        public int UserSMSID { get; set; }
        public string Tel { get; set; }
        public string Yanzhengma { get; set; }
        public int State { get; set; }
        public System.DateTime SentTime { get; set; }
        public string Ip { get; set; }
        public string SerialNumber { get; set; }
    }
}
