//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XFXClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExtend
    {
        public int UserID { get; set; }
        public int ExperienceValue { get; set; }
        public int ExperienceLevel { get; set; }
        public string ExperienceName { get; set; }
        public int Integral { get; set; }
        public int ComplaintSum { get; set; }
        public int ComplaintUntreated { get; set; }
        public int Banned { get; set; }
        public Nullable<System.DateTime> BannedStartTime { get; set; }
        public Nullable<System.DateTime> BannedEndTime { get; set; }
        public string Bust { get; set; }
        public string Waist { get; set; }
        public string Hips { get; set; }
        public string Stature { get; set; }
        public string Weight { get; set; }
        public string ProfessionalTitle { get; set; }
        public string ProfessionalDescription { get; set; }
    
        public virtual User User { get; set; }
    }
}
